---
title: "Lab 4 Slides"
author: "Natalie Cho"
date: "September 26 2022"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

## Slide 1

```{block, type="alert alert-info"}
#### Code Chunk 1
x = 1
y = 2
x+y
```

---
## Slide 2
```{block, type="alert alert-info"}
#### Code Chunk 2
z = 1
z+y
```

---
### Slide 3

```{block, type="alert alert-info"}
#### This is the last slide
```

---

